name: Publish

on:
  push:
    tags: ["*.*.*"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - uses: actions/setup-dotnet@v5

      - run: ./Build.ps1
        shell: pwsh

      - name: Docker login
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
        with:
          username: ${{ secrets.WORKLEAP_DOCKERHUB_USERNAME }}
          password: ${{ secrets.WORKLEAP_DOCKERHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6
        with:
          images: workleap/eventgridemulator

      - name: Docker build and push
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        with:
          context: ./src
          file: ./src/EventGridEmulator/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  linearb:
    needs: [publish]
    uses: workleap/wl-reusable-workflows/.github/workflows/linearb-deployment.yml@main
    with:
      environment: "release"
      cortexEntityIdOrTag: service-wl-eventgrid-emulator
    permissions:
      id-token: write
      contents: read
